
// Objective-C API for talking to the following Go packages
//
//	lex/rnwebserver/MyApp/webserver
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Webserver_FRAMEWORK_H__
#define __Webserver_FRAMEWORK_H__

#include "Webserver.objc.h"
#include "Universe.objc.h"

#endif
