// Objective-C API for talking to lex/rnwebserver/MyApp/webserver Go package.
//   gobind -lang=objc lex/rnwebserver/MyApp/webserver
//
// File is generated by gobind. Do not edit.

#ifndef __Webserver_H__
#define __Webserver_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * IsRunning
 */
FOUNDATION_EXPORT BOOL WebserverIsRunning(void);

/**
 * SetConfig
 */
FOUNDATION_EXPORT void WebserverSetConfig(NSString* _Nullable fileDir);

/**
 * Start
 */
FOUNDATION_EXPORT NSString* _Nonnull WebserverStart(NSError* _Nullable* _Nullable error);

/**
 * Stop
 */
FOUNDATION_EXPORT void WebserverStop(void);

/**
 * ServerUrl
 */
FOUNDATION_EXPORT NSString* _Nonnull WebserverUrl(void);

#endif
